version: "3.9"

services:
  springboot-docker-maven:
    image: springboot-docker-maven
    container_name: springboot-docker-maven-container
    build:
        context: .
        dockerfile: ../../../../IdeaProjects/CRUD_MAVEN/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
#    depends_on:
#        - mysql

#  mysql:
#    image: mysql
#    container_name: mysql_database
#    ports:
#      - "3307:3306"
#    networks:
#      - spring-network
#    volumes:
#      - mysql_volume:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 2004
#      MYSQL_DATABASE: docker_Maven
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 231222

networks:
  spring-network:
volumes:
  mysql_volume: